version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todo
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    command: ["sh", "-c", "pnpm install && pnpm run dev"]

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
