api_platform:
    title: ToDo API
    version: 1.0.0
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    keep_legacy_inflector: false
    use_symfony_listeners: true
    enable_swagger_ui: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
