lexik_jwt_authentication:
    secret_key:  '%kernel.project_dir%/config/jwt/private.pem'
    public_key:  '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: 'CUSTOM_PASS_PHRASE'
    token_ttl: 3600
    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
        cookie:
            enabled: false
        query_parameter:
            enabled: false
 